### ISSUE TITLE
Failed to install due to dependency issues

### ISSUE THREAD

**Issue by stborchert** [derhasi/toggl2redmine#11]
When trying to install toggle2redmine I get the following output/errors:

> Using version 0.2.* for derhasi/toggl2redmine
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>  Problem 1
>    - Conclusion: don't install derhasi/toggl2redmine 0.2.1
>    - Installation request for derhasi/toggl2redmine 0.2.* -> satisfiable by derhasi/toggl2redmine[0.2.0, 0.2.1].
>    - Conclusion: remove symfony/config v2.5.8
>    - derhasi/toggl2redmine 0.2.0 requires symfony/config 2.6.* -> satisfiable by symfony/config[v2.6.0, v2.6.1].
>    - Can only install one of: symfony/config[v2.6.0, v2.5.8].
>    - Can only install one of: symfony/config[v2.6.1, v2.5.8].
>    - Installation request for symfony/config == 2.5.8.0 -> satisfiable by symfony/config[v2.5.8].
>
>
> Installation failed, reverting ./composer.json to its original content.

I've installed _phpmd_ which requires symfony/config version 2.5.* (as per composer.json) ... maybe this is causing the problem here.
Trying **composer global update** didn't help.

**Comment by derhasi** [comment]
That's an issue due to different dependencies for symfony/config. PHPMD needs `2.5.*` which is not compatible with toggl2redmine's `2.6.*`.

**Comment by stborchert** [comment]
I've fixed this updating _phpmd_ to the latest development version.
