### ISSUE TITLE
Package guzzle/guzzle is abandoned.

### ISSUE THREAD

**Issue by KelvinWong** [derhasi/toggl2redmine#12]
Got an error during install.

```
$ composer global require derhasi/toggl2redmine

Nothing to install or update
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
```

**Comment by radimklaska** [comment]
guzzle/guzzle is not direct requirement of derhasi/toggl2redmine. It needs to be fixed here: https://github.com/arendjantetteroo/guzzle-toggl/issues/9 | https://github.com/arendjantetteroo/guzzle-toggl/blob/master/composer.json#L15

**Comment by arendjantetteroo** [comment]
v1.0 has been tagged which is based on guzzle 6, so this error should no longer appear if this library updates its dependencies.
